apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: adrian119/examplenode-dev:9
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
